# np.sort

In [5]:
import numpy as np

In [6]:
a=np.random.randint(1,100,15)
a

array([ 4, 20, 68, 69, 52, 60, 72, 32, 39, 97, 11, 48, 88, 27,  8])

In [7]:
b=np.random.randint(1,100,24).reshape(6,4)
b

array([[21, 83, 93, 19],
       [70, 57, 93, 55],
       [10, 61, 60,  3],
       [19, 82, 60, 73],
       [83, 16, 14, 88],
       [33, 65, 85, 50]])

In [8]:
np.sort(a)

array([ 4,  8, 11, 20, 27, 32, 39, 48, 52, 60, 68, 69, 72, 88, 97])

In [9]:
np.sort(b,axis=0)

array([[10, 16, 14,  3],
       [19, 57, 60, 19],
       [21, 61, 60, 50],
       [33, 65, 85, 55],
       [70, 82, 93, 73],
       [83, 83, 93, 88]])

In [10]:
np.sort(b,axis=1)

array([[19, 21, 83, 93],
       [55, 57, 70, 93],
       [ 3, 10, 60, 61],
       [19, 60, 73, 82],
       [14, 16, 83, 88],
       [33, 50, 65, 85]])

# np.concatenate

In [12]:
c=np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)

In [13]:
np.concatenate((c,d))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [14]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

# np.unique 

In [16]:
e=np.array([111,1,2,2,2,3,45,5,22,2,3.4,1,3,3,24,4,0],dtype=int)
np.unique(e)

array([  0,   1,   2,   3,   4,   5,  22,  24,  45, 111])

# np.expand_dim

In [18]:
a=np.array([1,2,3,4,5,6,7,8,9])
np.expand_dims(a,axis=0)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

# np.where

In [38]:
a=np.random.randint(1,1000,50)
a

array([613, 542, 374,  29, 356, 934, 784, 247, 402, 759, 424, 763, 500,
       532, 363, 149, 321, 599, 982, 436, 672, 875, 972, 377, 432, 527,
        96, 217,  52, 384, 461, 318, 515, 893, 751, 884, 764, 625, 224,
       805, 781, 201, 979, 408, 487, 667, 133, 245, 776, 771])

Selecting Elements from Two Arrays Based on a Condition
numpy.where(condition, x, y)




- **Parameters**:
  - `condition`: A boolean array or condition that evaluates to `True` or `False`.
  - `x`: An array from which to select values when the condition is `True`.
  - `y`: An array from which to select values when the condition is `False`.

- **Returns**: An array with elements from `x` where the condition is `True`, and elements from `y` where the condition is `False.

In [46]:
np.where(a>50,True,a)

array([ 1,  1,  1, 29,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

### `numpy.argmax`

The `numpy.argmax` function is used to find the indices of the maximum values along an axis in an array. It returns the index of the first occurrence of the maximum value.

In [50]:
np.argmax(a)

18

### `numpy.argmin`

The `numpy.argmim` function is used to find the indices of the min values along an axis in an array. It returns the index of the first occurrence of the maximum value.

In [56]:
np.argmin(a)

3

### `numpy.cumsum`

The `numpy.cumsum` function computes the cumulative sum of the elements along a given axis. It returns an array of the same shape as the input array, where each element at index `i` is the sum of the elements from the start of the array to index `i`.

#### Syntax
numpy.cumsum(a, axis=None, dtype=None, out=None)

In [58]:
np.cumsum(a)

array([  613,  1155,  1529,  1558,  1914,  2848,  3632,  3879,  4281,
        5040,  5464,  6227,  6727,  7259,  7622,  7771,  8092,  8691,
        9673, 10109, 10781, 11656, 12628, 13005, 13437, 13964, 14060,
       14277, 14329, 14713, 15174, 15492, 16007, 16900, 17651, 18535,
       19299, 19924, 20148, 20953, 21734, 21935, 22914, 23322, 23809,
       24476, 24609, 24854, 25630, 26401])

In [67]:
b=np.random.randint(1,100,30).reshape(5,6)
b

array([[55, 99,  9, 60, 24, 78],
       [53, 26, 78, 30, 17, 86],
       [52, 71, 49, 13, 66, 87],
       [61, 88, 72, 92, 94, 75],
       [ 2, 65, 93, 34, 97, 86]])

In [69]:
np.cumsum(b,axis=0)

array([[ 55,  99,   9,  60,  24,  78],
       [108, 125,  87,  90,  41, 164],
       [160, 196, 136, 103, 107, 251],
       [221, 284, 208, 195, 201, 326],
       [223, 349, 301, 229, 298, 412]])

In [71]:
np.cumsum(b,axis=1)

array([[ 55, 154, 163, 223, 247, 325],
       [ 53,  79, 157, 187, 204, 290],
       [ 52, 123, 172, 185, 251, 338],
       [ 61, 149, 221, 313, 407, 482],
       [  2,  67, 160, 194, 291, 377]])

### `numpy.percentile`

The `numpy.percentile` function is used to compute the nth percentile of the given data along a specified axis. A percentile is a measure used in statistics indicating the value below which a given percentage of observations in a group of observations falls.

### Syntax
numpy.percentile(a, q, axis=None, out=None, overwrite_input=False, interpolation='linear')




- **Parameters**:
  - `a`: Input array or object that can be converted to an array.
  - `q`: The percentile or sequence of percentiles to compute, which must be in the range [0, 100].
  - `axis`: Axis along which the percentiles are computed. By default, it flattens the array.
  - `out`: Optional output array to store the result.
  - `overwrite_input`: If True, allows the input array to be modified in place. This can save memory but may lead to loss of the original data.
  - `interpolation`: This parameter determines the interpolation method to use when the desired percentile lies between two data points. Options include:
    - `'linear'`: Default method.
    - `'lower'`: Returns the lower data point.
    - `'higher'`: Returns the higher data point.
    - `'nearest'`: Returns the nearest data point.
    - `'midpoint'`: Returns the average of the two data points.

- **Returns**: The computed percentile(s) as a scalar or an array, depending on the input.

In [74]:
a

array([613, 542, 374,  29, 356, 934, 784, 247, 402, 759, 424, 763, 500,
       532, 363, 149, 321, 599, 982, 436, 672, 875, 972, 377, 432, 527,
        96, 217,  52, 384, 461, 318, 515, 893, 751, 884, 764, 625, 224,
       805, 781, 201, 979, 408, 487, 667, 133, 245, 776, 771])

In [76]:
np.percentile(a,50)

507.5

In [78]:
np.median(a)

507.5

### `numpy.histogram`

In [87]:
np.histogram(a,bins=[0,100,100])

(array([3, 0], dtype=int64), array([  0, 100, 100]))

### `numpy.corrcoef`
The `numpy.corrcoef` function computes the correlation coefficients between two or more datasets. It returns a matrix of correlation coefficients, which indicates the strength and direction of the linear relationship between the datasets.

### Syntax
numpy.corrcoef(x, y=None, rowvar=True, bias=False, ddof=None)




- **Parameters**:
  - `x`: A 1D or 2D array containing the data. If `y` is not provided, `x` is treated as a 2D array where each row represents a variable and each column represents an observation.
  - `y`: An optional second dataset. If provided, it should be of the same length as the rows of `x`.
  - `rowvar`: If `True` (default), each row represents a variable, and each column represents an observation. If `False`, the roles are reversed.
  - `bias`: If `True`, the normalization is by `N` (the number of observations). If `False` (default), normalization is by `N-1`, which provides an unbiased estimate.
  - `ddof`: If specified, it is used in the calculation of the standard deviation.

- **Returns**: A 2D array of correlation coefficients. The element at the i-th row and j-th column represents the correlation coefficient between the i-th and j-th variables.

In [94]:
salary=np.array([20000,40000,25000,35000,600000])
experience=np.array([1,2,3,4,5])

In [96]:
np.corrcoef(salary,experience)

array([[1.        , 0.71606653],
       [0.71606653, 1.        ]])

### `numpy.isin`
The `numpy.isin` function is used to test whether elements of one array are present in another array. It returns a boolean array of the same shape as the first array, indicating whether each element is found in the second array.

### Syntax
numpy.isin(element, test_elements, assume_unique=False, invert=False)




- **Parameters**:
  - `element`: The input array containing the values to be tested.
  - `test_elements`: The array of values against which to test the elements of the first array.
  - `assume_unique`: If `True`, the input arrays are assumed to be unique, which can speed up the operation. Default is `False`.
  - `invert`: If `True`, the boolean array is inverted (i.e., `True` becomes `False` and vice versa). Default is `False`.

- **Returns**: A boolean array of the same shape as `element`, where each entry is `True` if the corresponding element is found in `test_elements`, and `False` otherwise.

In [101]:
a=np.random.randint(0,100,10)
a

array([86, 89, 14, 86, 91, 27, 36, 63, 55, 56])

In [115]:
items=[89,5,91,27,34,2342,234,2]

In [189]:
a[np.isin(a,items)]

array([89, 91, 27])

### `numpy.flip`

The `numpy.flip` function is used to reverse the order of elements in an array along a specified axis. This can be useful for various data manipulation tasks.

### Syntax
numpy.flip(m, axis=None)

Run code in Notebook



- **Parameters**:
  - `m`: Input array to be flipped.
  - `axis`: Axis or axes along which to flip the input array. By default, it flips the array along all axes.

- **Returns**: A new array with the same shape and type as `m`, with the specified axes flipped.

In [198]:
from icecream import ic
ic(a)
np.flip(a)

ic| a: array([86, 89, 14, 86, 91, 27, 36, 63, 55, 56])


array([56, 55, 63, 36, 27, 91, 86, 14, 89, 86])

In [202]:
ic(b)
np.flip(b)

ic| b: array([[55, 99,  9, 60, 24, 78],
              [53, 26, 78, 30, 17, 86],
              [52, 71, 49, 13, 66, 87],
              [61, 88, 72, 92, 94, 75],
              [ 2, 65, 93, 34, 97, 86]])


array([[86, 97, 34, 93, 65,  2],
       [75, 94, 92, 72, 88, 61],
       [87, 66, 13, 49, 71, 52],
       [86, 17, 30, 78, 26, 53],
       [78, 24, 60,  9, 99, 55]])

In [204]:
ic(b)
np.flip(b,axis=0)  # column filp

ic| b: array([[55, 99,  9, 60, 24, 78],
              [53, 26, 78, 30, 17, 86],
              [52, 71, 49, 13, 66, 87],
              [61, 88, 72, 92, 94, 75],
              [ 2, 65, 93, 34, 97, 86]])


array([[ 2, 65, 93, 34, 97, 86],
       [61, 88, 72, 92, 94, 75],
       [52, 71, 49, 13, 66, 87],
       [53, 26, 78, 30, 17, 86],
       [55, 99,  9, 60, 24, 78]])

In [206]:
ic(b)
np.flip(b,axis=1)  # row filp

ic| b: array([[55, 99,  9, 60, 24, 78],
              [53, 26, 78, 30, 17, 86],
              [52, 71, 49, 13, 66, 87],
              [61, 88, 72, 92, 94, 75],
              [ 2, 65, 93, 34, 97, 86]])


array([[78, 24, 60,  9, 99, 55],
       [86, 17, 30, 78, 26, 53],
       [87, 66, 13, 49, 71, 52],
       [75, 94, 92, 72, 88, 61],
       [86, 97, 34, 93, 65,  2]])

### `numpy.put`
The `numpy.put` function is used to insert values into an array at specified indices. It allows you to modify an existing array by placing new values at the given positions.

### Syntax
numpy.put(a, ind, v, mode='raise')




- **Parameters**:
  - `a`: The input array in which values will be placed.
  - `ind`: The indices at which to place the values. This can be a single index or an array of indices.
  - `v`: The values to be inserted into the array at the specified indices. The length of `v` should match the length of `ind`.
  - `mode`: This parameter determines how to handle out-of-bounds indices. It can take the following values:
    - `'raise'`: (default) Raises an error if an index is out of bounds.
    - `'wrap'`: Wraps around the index if it is out of bounds.
    - `'clip'`: Clips the index to the valid range.

- **Returns**: The modified array with the specified values inserted at the given indices.

In [209]:
a

array([86, 89, 14, 86, 91, 27, 36, 63, 55, 56])

In [215]:
np.put(a,[0,1],[110,555])   # modifying the original array.

In [217]:
a

array([110, 555,  14,  86,  91,  27,  36,  63,  55,  56])