In [43]:
import numpy as np
get_ipython().system('pip install icecream')
from icecream import ic
 

In [44]:
a=np.array([1,2,3,4,5])
a.ndim   #vector

1

In [45]:
#2d and 3d
b=np.array([[1,2,3],[4,5,6]])
b.ndim #matix

2

In [46]:
c=np.array([[[1,2,3],[3,4,5]],[[6,7,8],[8,9,0]]])
ic(c.ndim) #tensor
ic(c.dtype) #it will show the type of the element

ic| c.ndim: 3
ic| c.dtype: dtype('int32')


dtype('int32')

In [47]:
# dtype
c.astype(float)

array([[[1., 2., 3.],
        [3., 4., 5.]],

       [[6., 7., 8.],
        [8., 9., 0.]]])

In [48]:
d=np.array([[-1,2,3],[4,5,0]],dtype=bool)
ic(d)

ic| d: array([[ True,  True,  True],
              [ True,  True, False]])


array([[ True,  True,  True],
       [ True,  True, False]])

In [49]:
#arange ....it will act like range 
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [50]:
np.arange(0,10,2).astype(float)   # to change the dtype

array([0., 2., 4., 6., 8.])

In [51]:
# reshape # to change the shape 
np.arange(0,10).reshape([2,5])   # 2 x 5 = 10  ;;;;; 10 is equal to total number of elements
 
 

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [52]:
#np.ones and np.zeros
np.ones([3,4])
 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [53]:
 
np.ones([3,4],dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [54]:
np.zeros([5,4],dtype=bool)
 

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [55]:
# np.random 
np.random.random((2,3))

array([[0.31847875, 0.74581341, 0.41085657],
       [0.91182795, 0.83735303, 0.00351634]])

In [56]:
np.random.randint(5, size=(5,3))

array([[4, 0, 0],
       [3, 4, 2],
       [4, 1, 1],
       [2, 0, 1],
       [0, 1, 1]])

In [57]:
# np.linespace       ;;;; it will give linerly sapteare value in a range
np.linspace(5,10,20)

array([ 5.        ,  5.26315789,  5.52631579,  5.78947368,  6.05263158,
        6.31578947,  6.57894737,  6.84210526,  7.10526316,  7.36842105,
        7.63157895,  7.89473684,  8.15789474,  8.42105263,  8.68421053,
        8.94736842,  9.21052632,  9.47368421,  9.73684211, 10.        ])

In [58]:
#np.identity ;;;;; to make identity matix
np.identity(8,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

 # # Array Attibutes

 

In [60]:
# Create a 1D array 'a1' with values ranging from 0 to 9
a1 = np.arange(10)

# Create a 2D array 'a2' with values ranging from 12 to 23, reshaped into a 3x4 matrix
a2 = np.arange(12, dtype=float).reshape(3, 4)

# Create a 3D array 'a3' with values ranging from 0 to 7, reshaped into a 2x2x2 tensor
a3 = np.arange(8).reshape(2, 2, 2)

In [61]:
ic(a3)

ic| a3: array([[[0, 1],
                [2, 3]],
        
               [[4, 5],
                [6, 7]]])


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [62]:
#ndim and shape
ic(a3.ndim)
ic(a3.shape)

ic| a3.ndim: 3
ic| a3.shape: (2, 2, 2)


(2, 2, 2)

In [63]:
#size
ic(a3.size)
ic(a2.size)

ic| a3.size: 8
ic| a2.size: 12


12

In [64]:
#itemsize
ic(a3.itemsize) #INT
ic(a3.dtype)
ic(a2.itemsize) #float
ic(a2.dtype)
 

ic| a3.itemsize: 4
ic| a3.dtype: dtype('int32')
ic| a2.itemsize: 8
ic| a2.dtype: dtype('float64')


dtype('float64')

In [65]:
#change Datatype
#astype
a3.astype(np.float16)
 

array([[[0., 1.],
        [2., 3.]],

       [[4., 5.],
        [6., 7.]]], dtype=float16)

## Array Operation

In [67]:
b1=np.arange(12).reshape(3,4)
b2=np.arange(12,24).reshape(3,4)

In [68]:
# scalar operation
ic(b1 + 3)
 
#arithmatic
b1 **2

ic| b1 + 3: array([[ 3,  4,  5,  6],
                   [ 7,  8,  9, 10],
                   [11, 12, 13, 14]])


array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [69]:
# relational
b2>15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [70]:
#vector operations
b1 * b2
 

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [71]:
#max / min / sum / prod
np.max(b2)
 
 

23

In [72]:
np.min(b2)

12

In [73]:
np.sum(b1)

66

In [74]:
np.prod(b1)

0

In [75]:
ic(b2)
# 0 -> col and 1 -> row 
ic(np.max(b2,axis=0))
ic(np.max(b2,axis=1))

ic| b2: array([[12, 13, 14, 15],
               [16, 17, 18, 19],
               [20, 21, 22, 23]])
ic| np.max(b2,axis=0): array([20, 21, 22, 23])
ic| np.max(b2,axis=1): array([15, 19, 23])


array([15, 19, 23])

In [76]:
# mean /median /std/ var
np.mean(b1,axis=0)

array([4., 5., 6., 7.])

In [77]:
# dot product  a=2 X 3  b= 3 x 7 it will work  
b1=np.arange(12).reshape(3,4)
b2=np.arange(12,24).reshape(3,4)
np.dot(b1,b2)  # it wont work bsc b1=3 x 4   b2=3X4

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [78]:
b1=np.arange(12).reshape(3,4)
b2=np.arange(12,24).reshape(4,3)
np.dot(b1,b2)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [79]:
#log and exponents
np.log(b1)
 

C:\Users\karth\AppData\Local\Temp\ipykernel_17500\2835116542.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(b1)


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527]])

In [80]:
np.exp(b2)

array([[1.62754791e+05, 4.42413392e+05, 1.20260428e+06],
       [3.26901737e+06, 8.88611052e+06, 2.41549528e+07],
       [6.56599691e+07, 1.78482301e+08, 4.85165195e+08],
       [1.31881573e+09, 3.58491285e+09, 9.74480345e+09]])

In [81]:
# round / floor / ceil
 
(np.random.random((2,3))*100)

array([[63.01715139, 67.32192445, 91.57658952],
       [14.68975543, 72.67147481, 70.92818434]])

In [82]:
np.round((np.random.random((2,3))*100))


array([[28.,  2., 57.],
       [17., 78., 43.]])

In [83]:
 
np.floor((np.random.random((2,3))*100))



array([[67., 68., 34.],
       [ 8., 54., 62.]])

In [84]:
np.ceil((np.random.random((2,3))*100))

array([[78., 61., 32.],
       [33., 66., 18.]])

## indexing and slicing

In [86]:
a1 = np.arange(10)
a2 =np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [87]:

a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [88]:
ic(a[-1]) # last element

ic| a[-1]: 5


5

In [89]:
ic(a[0]) # first element

ic| a[0]: 1


1

In [90]:
ic(a2[1,2])
 

ic| a2[1,2]: 6


6

In [91]:
ic(a2[-1,-1])

ic| a2[-1,-1]: 11


11

In [92]:
ic(a3[-1,-2,-1])

ic| a3[-1,-2,-1]: 5


5

In [93]:
ic(a3[1,0,1])   #both or same

ic| a3[1,0,1]: 5


5

In [94]:
ic(a1)
a1[2:5]

ic| a1: array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


array([2, 3, 4])

In [95]:
ic(a2)
a2[0,1:]

ic| a2: array([[ 0,  1,  2,  3],
               [ 4,  5,  6,  7],
               [ 8,  9, 10, 11]])


array([1, 2, 3])

In [96]:
a2[1:,1:3]   #[rows,colums]

array([[ 5,  6],
       [ 9, 10]])

In [97]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [98]:
ic(a3)

ic| a3: array([[[0, 1],
                [2, 3]],
        
               [[4, 5],
                [6, 7]]])


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [99]:
a3=np.arange(27).reshape(3,3,3)

In [100]:
ic(a3)

ic| a3: array([[[ 0,  1,  2],
                [ 3,  4,  5],
                [ 6,  7,  8]],
        
               [[ 9, 10, 11],
                [12, 13, 14],
                [15, 16, 17]],
        
               [[18, 19, 20],
                [21, 22, 23],
                [24, 25, 26]]])


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [101]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [102]:
a3[0,1]

array([3, 4, 5])

In [103]:
a3[1,:,1]

array([10, 13, 16])

In [104]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [105]:
a3[::2,0,::2]     

array([[ 0,  2],
       [18, 20]])

# iterating

In [107]:
for i in a1:
    ic(i)

ic| i: 0
ic| i: 1
ic| i: 2
ic| i: 3
ic| i: 4
ic| i: 5
ic| i: 6
ic| i: 7
ic| i: 8
ic| i: 9


In [108]:
for item in a2:
    print(item)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [109]:
for i in a3:
   print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]
